# Generated by Django 3.2 on 2021-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_auto_20180424_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
