# Generated by Django 3.2 on 2021-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20200828_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='meta-information'),
        ),
    ]
