# Generated by Django 3.2 on 2021-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_log', '0002_auto_20210330_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlogentry',
            name='payload',
            field=models.JSONField(null=True, verbose_name='additional data'),
        ),
    ]
